// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521075240_SeedBooks")]
    partial class SeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Isbn = "ISBN0001",
                            PublicationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Isbn = "ISBN0002",
                            PublicationDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Isbn = "ISBN0003",
                            PublicationDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            Isbn = "ISBN0004",
                            PublicationDate = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            Isbn = "ISBN0005",
                            PublicationDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            Isbn = "ISBN0006",
                            PublicationDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            Isbn = "ISBN0007",
                            PublicationDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            Isbn = "ISBN0008",
                            PublicationDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            Isbn = "ISBN0009",
                            PublicationDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            Isbn = "ISBN0010",
                            PublicationDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            Isbn = "ISBN0011",
                            PublicationDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            Isbn = "ISBN0012",
                            PublicationDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            Isbn = "ISBN0013",
                            PublicationDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            Isbn = "ISBN0014",
                            PublicationDate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            Isbn = "ISBN0015",
                            PublicationDate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
